//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XwRemote.Misc.Poderosa.Plugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XwRemote.Misc.Poderosa.Plugin.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred. Please check {0} . 
        ///{1}.
        /// </summary>
        internal static string Message_Util_InternalError {
            get {
                return ResourceManager.GetString("Message.Util.InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly {0} was not able to be loaded..
        /// </summary>
        internal static string PluginManager_Messages_AssemblyLoadError {
            get {
                return ResourceManager.GetString("PluginManager.Messages.AssemblyLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poderosa starts ignoring plug-in {0}. .
        /// </summary>
        internal static string PluginManager_Messages_BootWithoutThisPlugin {
            get {
                return ResourceManager.GetString("PluginManager.Messages.BootWithoutThisPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following plug-ins are not able to be loaded due to the circular dependencies. {0}.
        /// </summary>
        internal static string PluginManager_Messages_DependencyLoopError {
            get {
                return ResourceManager.GetString("PluginManager.Messages.DependencyLoopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} on which plug-in {0} depends is missing. Poderosa starts ignoring it. .
        /// </summary>
        internal static string PluginManager_Messages_DependencyNotFound {
            get {
                return ResourceManager.GetString("PluginManager.Messages.DependencyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension point {0} overlaps. .
        /// </summary>
        internal static string PluginManager_Messages_DuplicatedExtensionPointID {
            get {
                return ResourceManager.GetString("PluginManager.Messages.DuplicatedExtensionPointID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:{1} for plug-in {0} overlaps. Poderosa starts ignoring it. .
        /// </summary>
        internal static string PluginManager_Messages_IDDuplication {
            get {
                return ResourceManager.GetString("PluginManager.Messages.IDDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID is not specified for plug-in {0}. Poderosa starts ignoring it. .
        /// </summary>
        internal static string PluginManager_Messages_IDNotFound {
            get {
                return ResourceManager.GetString("PluginManager.Messages.IDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load a type {0} because it doesn&apos;t have IPlugin interface..
        /// </summary>
        internal static string PluginManager_Messages_IPluginIsNotImplemented {
            get {
                return ResourceManager.GetString("PluginManager.Messages.IPluginIsNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The definition of a new extension point was attempted when the plug-in is not in the initializing state..
        /// </summary>
        internal static string PluginManager_Messages_NewExtensionPointOutsideInit {
            get {
                return ResourceManager.GetString("PluginManager.Messages.NewExtensionPointOutsideInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load a type {0} because PluginInfoAttribute is not provided..
        /// </summary>
        internal static string PluginManager_Messages_PluginInfoAttributeNotFound {
            get {
                return ResourceManager.GetString("PluginManager.Messages.PluginInfoAttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize plug-in {0}. .
        /// </summary>
        internal static string PluginManager_Messages_PluginInitializeFailed {
            get {
                return ResourceManager.GetString("PluginManager.Messages.PluginInitializeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load a type {1} from an assembly {0}. .
        /// </summary>
        internal static string PluginManager_Messages_TypeLoadError {
            get {
                return ResourceManager.GetString("PluginManager.Messages.TypeLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two extensions which have IGUIMessageLoop, {0} and {1}, were attempted to start at the same time. The latter is disregarded..
        /// </summary>
        internal static string PoderosaWorld_Messages_DuplicatedMessageLoopExtension {
            get {
                return ResourceManager.GetString("PoderosaWorld.Messages.DuplicatedMessageLoopExtension", resourceCulture);
            }
        }
    }
}
