//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XwRemote.Misc.Poderosa.Protocols {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings_ja {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings_ja() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XwRemote.Misc.Poderosa.Protocols.strings_ja", typeof(strings_ja).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cygwinへの接続 - 接続中 (Ctrl+Cで中止します).
        /// </summary>
        internal static string Caption_CygwinLoginDialog_ConnectingCygwin {
            get {
                return ResourceManager.GetString("Caption.CygwinLoginDialog.ConnectingCygwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFUへの接続 - 接続中 (Ctrl+Cで中止します).
        /// </summary>
        internal static string Caption_CygwinLoginDialog_ConnectingSFU {
            get {
                return ResourceManager.GetString("Caption.CygwinLoginDialog.ConnectingSFU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (SOCKSを使用).
        /// </summary>
        internal static string Caption_TCPTerminalConnection_UsingSOCKS {
            get {
                return ResourceManager.GetString("Caption.TCPTerminalConnection.UsingSOCKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Common_OK {
            get {
                return ResourceManager.GetString("Common.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 制限なし.
        /// </summary>
        internal static string Enum_IPVersionPriority_Both {
            get {
                return ResourceManager.GetString("Enum.IPVersionPriority.Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4のみ使用.
        /// </summary>
        internal static string Enum_IPVersionPriority_V4Only {
            get {
                return ResourceManager.GetString("Enum.IPVersionPriority.V4Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv6のみ使用.
        /// </summary>
        internal static string Enum_IPVersionPriority_V6Only {
            get {
                return ResourceManager.GetString("Enum.IPVersionPriority.V6Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高度な設定(&amp;A).
        /// </summary>
        internal static string Form_CygwinLoginDialog__advancedOptionCheck {
            get {
                return ResourceManager.GetString("Form.CygwinLoginDialog._advancedOptionCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホームディレクトリ(&amp;H).
        /// </summary>
        internal static string Form_CygwinLoginDialog__homeDirectoryLabel {
            get {
                return ResourceManager.GetString("Form.CygwinLoginDialog._homeDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シェルがうまく起動できないときはCygTermをコンパイルしなおしてください。.
        /// </summary>
        internal static string Form_CygwinLoginDialog__lMessage {
            get {
                return ResourceManager.GetString("Form.CygwinLoginDialog._lMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログの保存先(&amp;L).
        /// </summary>
        internal static string Form_CygwinLoginDialog__logFileLabel {
            get {
                return ResourceManager.GetString("Form.CygwinLoginDialog._logFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログの種別(&amp;T).
        /// </summary>
        internal static string Form_CygwinLoginDialog__logTypeLabel {
            get {
                return ResourceManager.GetString("Form.CygwinLoginDialog._logTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シェル(&amp;S).
        /// </summary>
        internal static string Form_CygwinLoginDialog__shellLabel {
            get {
                return ResourceManager.GetString("Form.CygwinLoginDialog._shellLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cygwinへの接続.
        /// </summary>
        internal static string Form_CygwinLoginDialog_TextCygwin {
            get {
                return ResourceManager.GetString("Form.CygwinLoginDialog.TextCygwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFUへの接続.
        /// </summary>
        internal static string Form_CygwinLoginDialog_TextSFU {
            get {
                return ResourceManager.GetString("Form.CygwinLoginDialog.TextSFU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホスト名 {0} のIPアドレスが取得できませんでした。.
        /// </summary>
        internal static string Message_AddressNotResolved {
            get {
                return ResourceManager.GetString("Message.AddressNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続はタイムアウトしました.
        /// </summary>
        internal static string Message_ConnectionTimedOut {
            get {
                return ResourceManager.GetString("Message.ConnectionTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続エラー.
        /// </summary>
        internal static string Message_CygwinLoginDialog_ConnectionError {
            get {
                return ResourceManager.GetString("Message.CygwinLoginDialog.ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホームディレクトリが入力されていません。.
        /// </summary>
        internal static string Message_CygwinLoginDialog_EmptyHomeDirectory {
            get {
                return ResourceManager.GetString("Message.CygwinLoginDialog.EmptyHomeDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シェルが入力されていません。.
        /// </summary>
        internal static string Message_CygwinLoginDialog_EmptyShell {
            get {
                return ResourceManager.GetString("Message.CygwinLoginDialog.EmptyShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cygterm.exeが見つかりません.
        /// </summary>
        internal static string Message_CygwinUtil_CygtermExeNotFound {
            get {
                return ResourceManager.GetString("Message.CygwinUtil.CygtermExeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cygwinとの接続中にエラーが発生しました。
        ///.
        /// </summary>
        internal static string Message_CygwinUtil_FailedToConnect {
            get {
                return ResourceManager.GetString("Message.CygwinUtil.FailedToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cygtermの実行に失敗しました.
        /// </summary>
        internal static string Message_CygwinUtil_FailedToRunCygterm {
            get {
                return ResourceManager.GetString("Message.CygwinUtil.FailedToRunCygterm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cygwinのレジストリキーがみつかりません。Cygwinが正しくインストールされていないと思われます。.
        /// </summary>
        internal static string Message_CygwinUtil_KeyNotFound {
            get {
                return ResourceManager.GetString("Message.CygwinUtil.KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} への接続ができませんでした。.
        /// </summary>
        internal static string Message_FailedToConnectAddress {
            get {
                return ResourceManager.GetString("Message.FailedToConnectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} のポート {1} への接続ができませんでした。.
        /// </summary>
        internal static string Message_FailedToConnectPort {
            get {
                return ResourceManager.GetString("Message.FailedToConnectPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSHサーバの公開鍵はssh_known_hostsに登録されていません。登録して続行しますか？.
        /// </summary>
        internal static string Message_HostKeyChecker_AskHostKeyRegister {
            get {
                return ResourceManager.GetString("Message.HostKeyChecker.AskHostKeyRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSHサーバの公開鍵はssh_known_hostsに登録されているものと異なります。更新して続行しますか？.
        /// </summary>
        internal static string Message_HostKeyChecker_AskHostKeyRenew {
            get {
                return ResourceManager.GetString("Message.HostKeyChecker.AskHostKeyRenew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シリアルポートの設定に失敗しました。.
        /// </summary>
        internal static string Message_SerialTerminalConnection_ConfigError {
            get {
                return ResourceManager.GetString("Message.SerialTerminalConnection.ConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シリアル接続の複製はできません。.
        /// </summary>
        internal static string Message_SerialTerminalConnection_ReproduceError {
            get {
                return ResourceManager.GetString("Message.SerialTerminalConnection.ReproduceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services for Unixとの接続中にエラーが発生しました。
        ///.
        /// </summary>
        internal static string Message_SFUUtil_FailedToConnect {
            get {
                return ResourceManager.GetString("Message.SFUUtil.FailedToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レジストリキー{0}がみつかりません。Services for Unixが正しくインストールされていないと思われます。.
        /// </summary>
        internal static string Message_SFUUtil_KeyNotFound {
            get {
                return ResourceManager.GetString("Message.SFUUtil.KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続を中止しました。.
        /// </summary>
        internal static string Message_SSHConnector_Cancelled {
            get {
                return ResourceManager.GetString("Message.SSHConnector.Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break信号の送信ができませんでした。SSHサーバがBreak信号をサポートしているか確認してください。.
        /// </summary>
        internal static string Message_SSHTerminalconnection_BreakError {
            get {
                return ResourceManager.GetString("Message.SSHTerminalconnection.BreakError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続を閉じるときにエラーが発生しました。.
        /// </summary>
        internal static string Message_SSHTerminalConnection_CloseError {
            get {
                return ResourceManager.GetString("Message.SSHTerminalConnection.CloseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH1で接続を複製するときはオプションのSSHタブでパスフレーズを記憶するようにしていないといけません。.
        /// </summary>
        internal static string Message_SSHTerminalConnection_ReproduceErrorOnSSH1 {
            get {
                return ResourceManager.GetString("Message.SSHTerminalConnection.ReproduceErrorOnSSH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH2で一度閉じた接続を複製するときはオプションのSSHタブでパスフレーズを記憶するようにしていないといけません。.
        /// </summary>
        internal static string Message_SSHTerminalConnection_ReproduceErrorOnSSH2 {
            get {
                return ResourceManager.GetString("Message.SSHTerminalConnection.ReproduceErrorOnSSH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuppressGoAheadの指定に失敗しました。.
        /// </summary>
        internal static string Message_Telnet_FailedToSendSuppressGoAhead {
            get {
                return ResourceManager.GetString("Message.Telnet.FailedToSendSuppressGoAhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ターミナルタイプの指定に失敗しました。.
        /// </summary>
        internal static string Message_Telnet_FailedToSendTerminalType {
            get {
                return ResourceManager.GetString("Message.Telnet.FailedToSendTerminalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィンドウサイズの指定に失敗しました。.
        /// </summary>
        internal static string Message_Telnet_FailedToSendWidnowSize {
            get {
                return ResourceManager.GetString("Message.Telnet.FailedToSendWidnowSize", resourceCulture);
            }
        }
    }
}
